name: Bug report
description: Report a crash, incorrect behavior, or regression in SlopSentinel.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

        If you can include a minimal repro (a small file or snippet) we can usually fix it quickly.

  - type: textarea
    id: bug
    attributes:
      label: Describe the bug
      description: What happened? What did you expect to happen?
      placeholder: |
        Running `slop scan .` fails with ...
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this repo, run ...
        2. With this config ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: |
        It should ...
    validations:
      required: false

  - type: input
    id: slopsentinel_version
    attributes:
      label: SlopSentinel version
      description: Output of `slop --version` (or `slopsentinel --version`).
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python version
      placeholder: "3.12.2"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Config snippet
      description: Paste your `[tool.slopsentinel]` config (redact secrets).
      render: toml
      placeholder: |
        [tool.slopsentinel]
        threshold = 60
        languages = ["python"]
    validations:
      required: false

