name: Feature request
description: Suggest a new feature or improvement.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve SlopSentinel.

        The best feature requests include a concrete use-case and an example.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: |
        In CI, I want to ...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like SlopSentinel to do?
      placeholder: |
        Add a flag ...
        Add a new output format ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: |
        I tried using ...
        A workaround is ...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, screenshots, sample output, etc.
    validations:
      required: false

